### PR TITLE
ci: approve integration tests

### PR DESCRIPTION
**Pull request by JDarDagran**
### Problem

Currently, there's no option to conveniently let new committers to either run integration tests (Airflow integration case) or use OL credentials to external services needed to run integration tests successfully (Spark integration case). The only solution we've had so far was https://github.com/jklukas/git-push-fork-to-upstream-branch but this was far from good.

### Solution

* Add approval steps before integration tests.
* Remove approval steps **if pipeline runs from someone with write access to the repo**

Several additional notes:
* **Most important** we should enable `Pass secrets to builds from forked pull requests` after merging this PR (solves Spark integration problem).
* Side-effect of changing `determine_changed_module` is a huge speedup (from ~1 min to literally seconds with added new step).
* I forced (with code change in circleCI config) to not remove approval steps just for test. You can check the result [here](https://app.circleci.com/pipelines/gh/OpenLineage/OpenLineage/8912/workflows/14897b21-7ae6-4726-9070-a73b6f0f23c3). Screenshot attached with task on hold waiting for approval: 
image

#### One-line summary:

Introduce approvals to integration tests in CI.

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [x] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [x] Your comment includes a one-liner for the changelog about the specific purpose of the change (_if necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2023 contributors to the OpenLineage project

### CODE REVIEW

**Comment by pawel-big-lebowski** [comment]
Amazing improvement @JDarDagran 🥇 
Six-star at least.

**Review by pawel-big-lebowski — APPROVED** [review]
pls wait some time to let others get familiar with PR before merging.

**Comment by mobuchowski** [comment]
@JDarDagran I would separate the tests that require those secrets, and not gate _all_ of them behind approval

**Comment by JDarDagran** [comment]
@mobuchowski I agree that separating integration tests based on their secret requirements would enhance our security posture and testing efficiency. I would suggest creating a separate PR to implement this improvement.

**Pull request merged**
