### PR TITLE
docs: add integration matrix.

### PR DESCRIPTION
**Pull request by JDarDagran**
### Problem

Current OL integration could be more readable including features they provide.

### Solution

Add table with integrations in readme file.

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [ ] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [ ] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] Your comment includes a one-liner for the changelog about the specific purpose of the change (_if necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2023 contributors to the OpenLineage project

### CODE REVIEW

**Review by merobi-hub — CHANGES_REQUESTED** [review]
Thank you for making this, @JDarDagran . It will be great to have it, and we've needed it for a while! My one quibble with the implementation is the footnotes. Instead of linking to footnotes, could you use plain text and put the notes right below the matrix? I worry that folks will not bother to click and won't see the information. Otherwise, this LGTM.

**Review by pawel-big-lebowski — APPROVED** [review]

**Comment by JDarDagran** [comment]
> Thank you for making this, @JDarDagran . It will be great to have it, and we've needed it for a while! My one quibble with the implementation is the footnotes. Instead of linking to footnotes, could you use plain text and put the notes right below the matrix? I worry that folks will not bother to click and won't see the information. Otherwise, this LGTM.

I did not find better solution, honestly. To me adding some plain text, e.g. below:

| Name| Table-level lineage| Column-level lineage |
| ----| ------------------ | -------------------- |
|[Apache Spark](https://github.com/OpenLineage/OpenLineage/tree/main/integration/spark)| :white_check_mark: | :white_check_mark:<sup>[1]</sup>|
|[Apache Airflow](https://github.com/OpenLineage/OpenLineage/tree/main/integration/airflow)| :white_check_mark: | :white_check_mark:<sup>[2]</sup> |
|[Dagster](https://github.com/OpenLineage/OpenLineage/tree/main/integration/dagster)| :white_check_mark: | :x: |
|[dbt](https://github.com/OpenLineage/OpenLineage/tree/main/integration/dbt) |:white_check_mark: | :x: |
|[Flink](https://github.com/OpenLineage/OpenLineage/tree/main/integration/flink)|:white_check_mark: | :x: |

[1]: Does not support `SELECT *` queries with JDBC.
[2]: Only for SQL-based operators (except BigQuery).


might be a bit confusing. I don't have strong opinion.

**Comment by merobi-hub** [comment]
I agree that with the brackets, etc., it's not ideal, so I would use a * and ** or plain 1 and 2 as the note anchors (without []) and simply a period after the numbers or nothing after the asterisks in the notes. This would be a typical approach in publishing. I don't think that would be confusing, but maybe try it and see what you think? Sorry to be difficult about this, but it wouldn't be a good idea to put these notes at the end, I think.

**Comment by merobi-hub** [comment]
@JDarDagran also, I would say "Supports SQL-based operators other than BigQuery" for the second one, FWIW

**Comment by JDarDagran** [comment]
@merobi-hub please let me know if that's acceptable :)

**Comment by merobi-hub** [comment]
LGTM, thank you @JDarDagran

**Review by merobi-hub — APPROVED** [review]
LGTM, thank you

**Pull request merged**
