### PR TITLE
improve iceberg integration tests

### PR DESCRIPTION
**Pull request by pawel-big-lebowski**
Signed-off-by: Pawel Leszczynski <leszczynski.pawel@gmail.com>

### Problem

 * rewrite iceberg integration tests from `SparkContainerIntegrationTest`

### Solution

> **Note:** All schema changes require discussion. Please [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for context.

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [x] Your changes are accompanied by tests (_if relevant_)
- [] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2023 contributors to the OpenLineage project

### CODE REVIEW

**Comment by pawel-big-lebowski** [comment]
Integrations test took less than 10mins. This used to be 15mins or sometimes even more (16,18) in the past.  

There are still couple of hive tests in SparkContainerIntegration test that could be rewritten to SparkSession test suite. 

Screenshot 2023-01-20 at 15 06 24

**Comment by pawel-big-lebowski** [comment]
Possible future improvements:
* create separate ci workflow for `sql` which is now part of `java`,
* rewrite hive tests from `SparkContainerIntegrationTest` to some `SparkHiveIntegrationTest` that uses SparkAgent instead of docker container per each test,
* tag column lineage tests as `integration-test`
* is there any reason to run unit-tests per spark version? There used to be such a reason before submodule refactor. Now a single build should be enough. 
* Integration tests do not have to be run after `build-integration-test`. They can be run at the same time as there is no dependency between them. 
* take a look why `build` takes 7-8 mins.

**Comment by mobuchowski** [comment]
>

**Comment by mobuchowski** [comment]
>create separate ci workflow for sql which is now part of java

I think it won't work when we start to use sql parser in JDBCRelation.

**Review by mobuchowski — APPROVED** [review]

**Pull request merged**
