### PR TITLE
python: relax client requirements

### PR DESCRIPTION
**Pull request by mobuchowski**
Signed-off-by: Maciej Obuchowski <maciej.obuchowski@getindata.com>

### CODE REVIEW

**Comment by mobuchowski** [comment]
@wslulciuc can we merge this? The failing java release is due to RC release https://github.com/OpenLineage/OpenLineage/releases/tag/0.0.1-rc6

**Review by wslulciuc — APPROVED** [review]
LGTM 👍

**Comment by wslulciuc** [comment]
@mobuchowski: This looks good to merge, but looks like `release-java` is failing but probably shouldn't run for PRs?

**Comment by mobuchowski** [comment]
@wslulciuc it run for tag, not for PR - but github UI shows them together, as the PR/branch and tag resolves to same commit.

**Pull request merged**
