### PR TITLE
spark: integration test case for drop table

### PR DESCRIPTION
**Pull request by savannavalgi**
### Problem

drop table integration test did not verify the drop table events generated by openlineage.

Closes: #2143

### Solution

for drop table the  COMPLETE event generated has empty inputs and outputs facet.

but the START event has the table to be dropped/deleted in the outputs facet and  a empty inputs facet.

#### One-line summary:
added START event for the drop table integration test

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [x] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [x] You've updated any relevant documentation (_if relevant_)
- [x] Your comment includes a one-liner for the changelog about the specific purpose of the change (_if necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2023 contributors to the OpenLineage project

### CODE REVIEW

**Comment by merobi-hub** [comment]
Hi @savannavalgi , welcome to the OpenLineage community! Have you joined our [Slack](https://bit.ly/lineageslack) yet? It's the best way to stay-up-date on upcoming additions, releases, meetups, and more.

**Comment by pawel-big-lebowski** [comment]
Looks like there is an issue with `drop table` which makes the test fail.

**Comment by mobuchowski** [comment]
@savannavalgi please reopen the PR if you want to get back to it

**Comment by savannavalgi** [comment]
#2716 

Raised an issue with Spark to track this further: https://issues.apache.org/jira/browse/SPARK-48390

**Pull request closed without merging**
