### PR TITLE
changed url.getFile instead of url.toURI to fix build on windows

### PR DESCRIPTION
**Pull request by Arnaud-Nauwynck**
On windows  (cygwin anyway), I was getting build error

```
gradle build
..
> Task :generateCode FAILED
io.openlineage.client.Generator.main [file:C:\OpenLineage\client\java/../../spec/OpenLineage.json, file:C:\OpenLineage\client\java/../../spec/]
Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical
        at java.io.File.<init>(File.java:420)
        at io.openlineage.client.Generator.main(Generator.java:55)

FAILURE: Build failed with an exception.

```
with the small change, I get
```
BUILD SUCCESSFUL in 7s
6 actionable tasks: 6 executed
```

### CODE REVIEW

**Comment by mobuchowski** [comment]
Hey @Arnaud-Nauwynck , could you please follow the instructions to sign your commits here:
https://github.com/OpenLineage/OpenLineage/pull/303/checks?check_run_id=3688378640

**Review by julienledem — APPROVED** [review]
Thank you @Arnaud-Nauwynck !
Please follow @mobuchowski ' s instructions and we can merge.

**Comment by wslulciuc** [comment]
@Arnaud-Nauwynck: It'd be great to merge your fix! Mind running the following 2 commands on your branch to ensure the DCO check passes?

```
$ git rebase HEAD~2 --signoff
$ git push --force-with-lease origin main
```

**Comment by julienledem** [comment]
@Arnaud-Nauwynck We'd love to merge your PR. It just needs to be signed off. It should be quick. look at the message above.

**Review by wslulciuc — APPROVED** [review]
LGTM 👍

**Comment by mobuchowski** [comment]
Merged in https://github.com/OpenLineage/OpenLineage/pull/429

**Pull request closed without merging**
