### PR TITLE
Support ParentRunFacet for Databricks' Synapse DW Connector in Spark

### PR DESCRIPTION
**Pull request by wjohnson**
### Problem

The Datbaricks Synapse Data Warehouse Connector does not report lineage cleanly when Synapse is the output destination. The SparkSQLExecutionStart contains the correct output but the subsequent JobStart events contain lineage for a temporary folder. However, the JobStart event does report a `spark.sql.execution.parent` property which can be used to identify which parent execution id called this JobStart.

It doesn't close but it is a candidate for #670 for the Synapse DW Connector specifically.

### Solution

I plan to modify `SparkSQLExecutionContext.start(jobStart)` to do the following:
* Check if the Job Start event has the `spark.sql.execution.parent` property.
* If so, get the OpenLineage RunId for this execution Id. **Need help here**
* If there is a parent run, modify the call to `runEventBuilder.buildRun` and the `buildParentFacet` to accept:
  * Optional<UUID> parentRunID (this is provided by the above steps if I can figure them out)
  * String parentJobName (**Need help here**)
    * job Name seems to be buried in `SparkSqlExecutionContext.buildJob`  
    ```
    sparkContext.appName().replaceAll(CAMEL_TO_SNAKE_CASE, "_$1").toLowerCase(Locale.ROOT)
    + "."
    + node.nodeName().replaceAll(CAMEL_TO_SNAKE_CASE, "_$1").toLowerCase(Locale.ROOT));
    ```

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

### Checklist

- [ ] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [ ] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [ ] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)

### CODE REVIEW

**Comment by collado-mike** [comment]
Seems a good time to start refactoring the `ParentRunFacet` to be generated by an `AbstractRunFacetBuilder` rather than treating it as a special case the way we do. Currently, we hold that `parentRunId` in the `EventEmitter`, as we parse the Spark configuration at startup. Instead, we can move that logic to a new `AbstractRunFacetBuilder`. A tricky consideration is how to allow the default behavior when there is no databricks-specified parent execution id, but execute the custom builder when there is. I hate to rely on the order of execution (let the default run first, then override the facet map when the custom builder runs). Franky, I'm not opposed to putting all the logic in one facet builder; it just means that _only_ the databricks case is handled. Maybe that's ok, as we don't know of any other cases to handle.

**Comment by wjohnson** [comment]
> Seems a good time to start refactoring the `ParentRunFacet` to be generated by an `AbstractRunFacetBuilder` ... A tricky consideration is how to allow the default behavior when there is no databricks-specified parent execution id, but execute the custom builder when there is. ... I'm not opposed to putting all the logic in one facet builder; it just means that _only_ the databricks case is handled. Maybe that's ok, as we don't know of any other cases to handle.

I've been exploring this route for a bit and my one challenge is getting the Parent Run Id.

* JobStart contains the `spark.sql.execution.parent` and the execution id of the jobStart.
* I need to get the UUID for the ParentRun.
* I can only get the ParentRun by getting the SparkSqlExectutionContext which has an OpenLineageContext which has an OpenLineage which has the RunId but parts of this chain are consider private fields.
* To get that SparkSqlExecutionContext, I need to work with the `sparkSqlExecutionRegistry` field in the `OpenLineageSparkListener`.

I can put together a `DatabricksParentRunFacetBuilder` but I don't know how to extract that parent run id when it's stuck inside the OpenLineageSparkListener.

**Comment by collado-mike** [comment]
> I can put together a `DatabricksParentRunFacetBuilder` but I don't know how to extract that parent run id when it's stuck inside the OpenLineageSparkListener.

I was thinking to eliminate all references to the parent in the `OpenLineageSparkListener` - remove the spark configuration parsing, remove it from the `SparkSQLExecutionContext`, the `OpenLineageRunEventBuilder`... everything. Make a facet builder something like the following
```java
public class ParentRunFacetBuilder extends AbstractRunFacetBuilder<SparkListenerEvent> {
  private static final Map<Long, UUID> executionIdToRunIdMap = new ConcurrentHashMap<>();

  public ParentRunFacetBuilder(@NonNull OpenLineageContext context) {
    super(context);
  }

  @Override
  protected void build(SparkListenerEvent event, BiConsumer<String, ? super RunFacet> consumer) {
    context.getSparkSession()
        .ifPresent(sess -> {
          Optional<ParentRunFacet> parentFacet = buildParentFacet(sess);
          parentFacet.ifPresent(facet -> consumer.accept("parent", facet));
        });
  }

  private Optional<ParentRunFacet> buildParentFacet(SparkSession sess) {
    String parentRunId = SparkConfUtils.findSparkConfigKey(sess.sparkContext().conf(),
        "openlineage.parentRunId",
        null);
    String parentJobName = SparkConfUtils.findSparkConfigKey(
        sess.sparkContext().conf(),
        "openlineage.parentJobName",
        null
    );
    String namespace = SparkConfUtils.findSparkConfigKey(
        sess.sparkContext().conf(),
        "openlineage.namespace",
        null
    );
    if (parentRunId != null && parentJobName != null && namespace != null) {
      return Optional.of(context.getOpenLineage().newParentRunFacetBuilder()
          .run(context.getOpenLineage()
              .newParentRunFacetRunBuilder()
              .runId(UUID.fromString(parentRunId))
              .build())
          .job(context.getOpenLineage()
              .newParentRunFacetJobBuilder()
              .namespace(namespace)
              .name(parentJobName)
              .build())
          .build());
    }
    return Optional.empty();
  }
}
```
This will find the parent id and set it into the run facets.

What this _doesn't_ do is track the run ids of previous jobs and make it available for lookup. We could do something "hacky" and add a Map that tracks execution ids and the run ids associated with them - somewhat similar to how the unknown facet listener works. There's just not an easy way to make two different run facet builders - one for general purpose use and one for Databricks. But again, I don't know of any other scenario we need to handle, so maybe just a single facet builder with the logic for both scenarios is enough.

**Comment by wjohnson** [comment]
> What this _doesn't_ do is track the run ids of previous jobs and make it available for lookup. We could do something "hacky" and add a Map that tracks execution ids and the run ids associated with them - somewhat similar to how the unknown facet listener works.
@collado-mike I ran with an idea @mobuchowski had on the issue. This still doesn't quite do the trick because I don't provide namespace or name of the parent job.  Mind taking a look at the approach?  It does not conform to your approach 😰

I ended up modifying the ExecutionContext interface so that I could get a RunId from it.  And I use the sparkSqlExecutionRegistry to get the parent Run Id that is happening internally. I'm thinking I would do the same thing for job name (namespace name should be the same as normal I think) but haven't gotten that far yet.

**Comment by wjohnson** [comment]
Abandoning this one in favor of #849

**Pull request closed without merging**
