### PR TITLE
airflow: new extractor for S3ToSnowflakeOperator

### PR DESCRIPTION
**Pull request by manmeetkaur**
Signed-off-by: Manmeet Kaur <manmeetkaur.rangoola@gmail.com>

### Problem

This is related to this issue #1335 . It only covers a part of it, I intend to add more Extractors in this PR but want to get feedback on one first before proceeding ahead. 

Closes: 

### Solution

Includes just adding an extractor for `S3ToSnowflakeOperator` using the existing extractors or utilities. Tested on my local using Marquez using S3 Object Storage and Snowflake Account.

### Checklist

- [X] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [ ] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [ ] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2022 contributors to the OpenLineage project

### CODE REVIEW

**Comment by mobuchowski** [comment]
Hey @manmeetkaur , there are mypy errors: https://app.circleci.com/pipelines/github/OpenLineage/OpenLineage/5575/workflows/3ca25a15-61d9-407c-9726-a926ef6b7ae2/jobs/77512

**Comment by manmeetkaur** [comment]
> Hey @manmeetkaur , there are mypy errors: https://app.circleci.com/pipelines/github/OpenLineage/OpenLineage/5575/workflows/3ca25a15-61d9-407c-9726-a926ef6b7ae2/jobs/77512

Hey @mobuchowski Sorry for ghosting on this. I fixed the `mypy` issue, but now getting error in dagster tests section, can you provide guidance there ?

**Comment by manmeetkaur** [comment]
> Hey @manmeetkaur. Can you first rebase your work on latest main branch?

@mobuchowski rebase done. no changes

**Comment by manmeetkaur** [comment]
resolved all the ruff errors, now getting ```py3-airflow-2.5.0: commands[0]> flake8 --extend-exclude tests/integration,scripts/
py3-airflow-2.5.0: commands[1]> bash -ec 'if [[ ! -f $0/airflow.db ]]; then airflow db reset -y; fi' /home/circleci/openlineage/integration/airflow/.tox/py3-airflow-2.5.0
py3-airflow-2.5.0: failed with bash is not allowed, use allowlist_externals to allow it
  py3-airflow-2.5.0: FAIL code 1 (116.01 seconds)
  evaluation failed :( (116.09 seconds)

Exited with code exit status 1
```

**Comment by mobuchowski** [comment]
Hey @manmeetkaur I think it would be fixed if you rebased the code, where we've fixed this problem before. I see the first commits in this PR are still from December 7th - this means it's running against over 2 months old pipeline.
```
git rebase --onto main HEAD~7
```

**Pull request closed without merging**
