### PR TITLE
[SPARK][FLINK][JAVA] http timeout fix

### LINKED ISSUE #2474: `HttpTransport` timeout unit unclear
In the `HttpTransport`, the docs specify `millis` as the unit, see [`HttpTransport.withTimeout(Double)`](https://github.com/OpenLineage/OpenLineage/blob/main/client/java/src/main/java/io/openlineage/client/transports/HttpTransport.java#L53), but if the timeout is overwritten, the client multiples the timeout * `1000`:

```
private static CloseableHttpClient withTimeout(Double timeout) {
    int timeoutMs;
    if (timeout == null) {
      timeoutMs = 5000;
    } else {
      timeoutMs = (int) (timeout * 1000);
    }
...
```

* Why do we use `double`, not `int`?
* If a user passes `2000`, the timeout would be (based on the above) `2000` * `1000` = `2000000`

### PR DESCRIPTION
**Pull request by pawel-big-lebowski**
### Problem

Documentation says timeout should be provided in millis
Screenshot 2024-02-28 at 09 56 37

But the code treats it as if it was provided in seconds 

Fixes #2474

### Solution

 * Write failing test
 * Modify the code 

> **Note:** All schema changes require discussion. Please [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for context.

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

### Checklist

- [ ] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [ ] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [ ] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] Your comment includes a one-liner for the changelog about the specific purpose of the change (_if necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2023 contributors to the OpenLineage project

### CODE REVIEW

**Comment by mobuchowski** [comment]
@pawel-big-lebowski I think we should do this other way around and make docs fit the reality rather than breaking the timeout for people using floats

**Comment by pawel-big-lebowski** [comment]
> @pawel-big-lebowski I think we should do this other way around and make docs fit the reality rather than breaking the timeout for people using floats

@mobuchowski  I was thinking about this as well and I think we shouldn't. Suppose there's a user who configured timeout to 10000 and lives unaware of the fact timeout settings will not work. Once we fix it, timeout will work again. If we change the behaviour, timeout settings for such users will get broken even more. 

So the tradeoff is: shall we break the contract for those who follow the docs and are unaware of the problem or shall we break the contract for those (probably a single user) who found out the cause and hacked the system?

Additionally, circuit breaker timeout also uses milliseconds.

**Comment by d-m-h** [comment]
My 2 cents:

1. Add an explicit configuration to specify the time unit (minutes, seconds, milliseconds)
2. Default the above time unit to milliseconds
3. Allow users to configure accordingly.

This way, you remove the ambiguity of "is this 5 milliseconds, or 5 seconds?"

**Comment by pawel-big-lebowski** [comment]
Nice idea from offline discussions to make as many people happy as possible
 * We leave `timeout` as is in http config (treat it in seconds, remove it from docs), we mark config entry deprecated in the code
 * We include `timeoutMillis`  config entry and take its value for timeout if it's present

@mobuchowski would it make sense to you?

**Comment by tatiana** [comment]
> Nice idea from offline discussions to make as many people happy as possible
> 
> * We leave `timeout` as is in http config (treat it in seconds, remove it from docs), we mark config entry deprecated in the code
> * We include `timeoutMillis`  config entry and take its value for timeout if it's present
> 
> @mobuchowski would it make sense to you?

I really like this strategy, @pawel-big-lebowski , since it is backwards compatible and also supports users specifying milliseconds. Credits to @julienledem from our chat yesterday :D

**Pull request merged**
