### PR TITLE
Add Slack archive and dependency for viewing

### PR DESCRIPTION
**Pull request by merobi-hub**
### Problem

Being on Slack's free plan means that we lack access to threads and messages that are more than 3 months old.

### Solution

This adds two possible solutions to dev: 1) an exported zip archive from Slack with a dependency, [slack-export-viewer](https://github.com/hfaran/slack-export-viewer), to enable viewing the archive in a browser. If the community likes this approach, the entire history of public channels could be added to dev and updated on a regular basis. Instructions for using the package are in the readme; 2) the HTML generated by an alternative tool, [slack-archive](https://github.com/felixrieseberg/slack-archive).

The slack-archive tool is more fully-featured, but using it requires elevated permissions in Slack and the HTML its UI requires is voluminous (only one month's worth of Slack data is included here, and it amounts to close to 90k lines). Also, a user could accidentally share DMs and messages in private channels. By contrast, the slack-export-viewer tool does not require any permissions -- only an exported archive that those with admin privileges in the Slack workspace can generate -- and collects/displays only public channels. A screenshot of each is included below in the comments.  

> **Note:** All schema changes require discussion. Please [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for context.

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

### Checklist

- [ ] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [x] You've updated any relevant documentation (_if relevant_)
- [ ] Your comment includes a one-liner for the changelog about the specific purpose of the change (_if necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2023 contributors to the OpenLineage project

### CODE REVIEW

**Comment by merobi-hub** [comment]
Screenshot 2023-11-17 at 09 30 55

**Comment by merobi-hub** [comment]
HTML generated by slack-archive:
Screenshot 2023-11-18 at 14 08 28

**Comment by merobi-hub** [comment]
Update: I contributed a change to slack-export-viewer that improves the way it displays threads. It's been merged but not yet released.

**Comment by harels** [comment]
should we close this in favor of https://github.com/OpenLineage/slack-archives?

**Pull request closed without merging**
