### PR TITLE
airflow: Use threadpool-based event emission in Airflow 2.5

### PR DESCRIPTION
**Pull request by JDarDagran**
Signed-off-by: Jakub Dardzinski <kuba0221@gmail.com>
Credits to: Maciej Obuchowski @mobuchowski 
### Problem

Airflow 2.5 added proper lifecycle methods to plugins. This means we can properly start-and-stop thread pool, without risk that tasks send to it would get killed before the worker process ends. This resolves issue with long running extractions and thread blocks.

Closes: #1226 

### Solution

Create `ThreadPoolExecutor` in lifecycle hooks and submit extraction methods to the pool

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [x] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [x] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2022 contributors to the OpenLineage project

### CODE REVIEW

**Comment by ThomasBombeke** [comment]
Why was this PR closed? Is the issue of deadlocking fixed or being fixed in another PR?

**Comment by harels** [comment]
That right @ThomasBombeke.
We're tracking it here: https://github.com/OpenLineage/OpenLineage/issues/1226
and here https://github.com/OpenLineage/OpenLineage/issues/1435

**Comment by ThomasBombeke** [comment]
Do you have any rough timeline on this? We are looking to use OpenLineage but this deadlocking issue is a major blocker

**Comment by JDarDagran** [comment]
@ThomasBombeke there was [#29289](https://github.com/apache/airflow/pull/29289) PR in Airflow required to fix that. AFAIK this is going to be released in 2.6. Starting from this version this should be fixed.

**Comment by ThomasBombeke** [comment]
thanks for the information!

**Comment by ThomasBombeke** [comment]
Sorry one more question. Do you mean you can start working on the fix after Airflow 2.6 release or it is already fixed when bumping to Airflow 2.6?

**Comment by JDarDagran** [comment]
We can probably have a PR prepared and release OL with a support for that fix once Airflow 2.6 is out.

**Comment by JDarDagran** [comment]
@seanmuth  there's ongoing process of implementing OpenLineage as the Airflow provider (per [AIP-53](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-53+OpenLineage+in+Airflow)) which solves the issue completely.

**Pull request closed without merging**
