### PR TITLE
spark: add runtime property facet

### PR DESCRIPTION
**Pull request by Ruihua98**
#### Summary:
Add a new facet called RuntimePropertyFacet to capture RuntimeConfig of Spark session, because the existing SparkPropertyFacet can only capture static config of spark context.
This Facet will be added in both RDD-related runs and SQL-related runs. Users can use this feature by setting spark.openlineage.capturedRuntimeProperties.

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

#### One-line summary:
Add a new facet called RuntimePropertyFacet to capture RuntimeConfig of Spark session.

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [x] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [x] You've updated any relevant documentation (_if relevant_)
- [x] Your comment includes a one-liner for the changelog about the specific purpose of the change (_if necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [x] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2023 contributors to the OpenLineage project

### CODE REVIEW

**Comment by d-m-h** [comment]
Hi @Ruihua98 - thanks for your contribution. Going over your code, it seems your justification for creating this is only because the existing `integration/spark/shared/src/main/java/io/openlineage/spark/agent/facets/builder/SparkPropertyFacetBuilder.java` file uses 'SparkContext' and in your approach you are using `SparkSession`?

I'm not sure I fully understand what this is attempting to do then, because the `SparkConf` object is shared between the `SparkSession` and `SparkContext` objects.

Could you elaborate a bit more on where the current approach falls short?

**Comment by mobuchowski** [comment]
@Ruihua98 to be honest, I was thinking more of modifying existing `SparkPropertyFacetBuilder` to additionally capture runtime properties and adding it to RDDExecutionContext. Are there some problems with doing it that way? I don't think it breaks anything, although I might be wrong.

**Comment by Ruihua98** [comment]
> @Ruihua98 to be honest, I was thinking more of modifying existing `SparkPropertyFacetBuilder` to additionally capture runtime properties and adding it to RDDExecutionContext. Are there some problems with doing it that way? I don't think it breaks anything, although I might be wrong.

Hi~ We agree to modify the existing facet to achieve this. In fact, I have tried to write a [draft](https://github.com/OpenLineage/OpenLineage/compare/main...Ruihua98:OpenLineage:1.3.1-mod1) before I submit this PR. I found the code in that draft branch a little bit redundant. 
1.  I don't know how to use SparkPropertyFacetBuilder in RddExecutionContext because I didn't find  OpenLineageContext object in RddExecutionContext and this object is a parameter in SparkPropertyFacetBuilder's constructor method. 
2.  I don't know how to deal with these lines of code in SparkPropertyFacetBuilder because I didn't find event.properties() in SparkListenerEvent object. (maybe I was wrong here)
` event.properties().entrySet().stream().filter(e -> allowerProperties.contains(e.getKey())).forEach(e -> m.putIfAbsent(e.getKey().toString(), e.getValue()))`

The two reasons above make the code in my draft branch complex, so I finally submit a new facet. I fully agree to change my code to modify the old facet if you can help me find out how to solve the above two problems.

**Comment by mobuchowski** [comment]
>I don't know how to use SparkPropertyFacetBuilder in RddExecutionContext because I didn't find OpenLineageContext object in RddExecutionContext and this object is a parameter in SparkPropertyFacetBuilder's constructor method.

Feel free to add, for example `SparkPropertyRddExecutionFacetBuilder` that would accept objects that you need to construct the facet, or modify `SparkPropertyFacetBuilder` to be able to use it from both contexts.
For example, `OpenLineageContext` is used only to get `SparkConf` which could be passed directly:
```
    conf = context.getSparkContext().getConf();
```

>I don't know how to deal with these lines of code in SparkPropertyFacetBuilder because I didn't find event.properties() in SparkListenerEvent object. (maybe I was wrong here)
 event.properties().entrySet().stream().filter(e -> allowerProperties.contains(e.getKey())).forEach(e -> m.putIfAbsent(e.getKey().toString(), e.getValue()))
 
This code assumes that it's called with particular `SparkListenerJobStart` event, not generic `SparkListenerEvent`. If you need to emit this on other events, then two options would be to either add different `FacetBuilder` without that assumption, or modify code to check if event is `SparkListenerJobStart` using `instanceof`, and only adding those properties in that case.

I would go with modifying existing `SparkPropertyFacetBuilder`, because then there is no worry what happens if both try to add the same facet.

**Comment by Ruihua98** [comment]
> > I don't know how to use SparkPropertyFacetBuilder in RddExecutionContext because I didn't find OpenLineageContext object in RddExecutionContext and this object is a parameter in SparkPropertyFacetBuilder's constructor method.
> 
> Feel free to add, for example `SparkPropertyRddExecutionFacetBuilder` that would accept objects that you need to construct the facet, or modify `SparkPropertyFacetBuilder` to be able to use it from both contexts. For example, `OpenLineageContext` is used only to get `SparkConf` which could be passed directly:
> 
> ```
>     conf = context.getSparkContext().getConf();
> ```
> 
> > I don't know how to deal with these lines of code in SparkPropertyFacetBuilder because I didn't find event.properties() in SparkListenerEvent object. (maybe I was wrong here)
> > event.properties().entrySet().stream().filter(e -> allowerProperties.contains(e.getKey())).forEach(e -> m.putIfAbsent(e.getKey().toString(), e.getValue()))
> 
> This code assumes that it's called with particular `SparkListenerJobStart` event, not generic `SparkListenerEvent`. If you need to emit this on other events, then two options would be to either add different `FacetBuilder` without that assumption, or modify code to check if event is `SparkListenerJobStart` using `instanceof`, and only adding those properties in that case.
> 
> I would go with modifying existing `SparkPropertyFacetBuilder`, because then there is no worry what happens if both try to add the same facet.

Thank you very much. I have finished another version by only modifying existing `SparkPropertyFacetBuilder` with your help. [New Branch](https://github.com/Ruihua98/OpenLineage/tree/feature/modify-spark-property-facet) Should I end this PR and create a new PR on the new branch?

**Comment by mobuchowski** [comment]
@Ruihua98 either open a new PR or push changes to this one, I'm okay with both :)

**Comment by Ruihua98** [comment]
> Add a new facet called RuntimePropertyFacet to capture RuntimeConfig of Spark session, because the existing SparkPropertyFacet can only capture static config of spark context.
> This Facet will be added in both RDD-related runs and SQL-related runs.

I have submitted a New PR https://github.com/OpenLineage/OpenLineage/pull/2480 , and this old one can be closed.

**Pull request closed without merging**
