### PR TITLE
sql: add support for Apple Silicon to openlineage-sql-java

### PR DESCRIPTION
**Pull request by davidjgoss**
### Problem

The [Java wrapper for the SQL integration](https://central.sonatype.com/artifact/io.openlineage/openlineage-sql-java) doesn't work on Macs with Apple Silicon, as a binary is only distributed for Intel Macs - currently running it will result in an `UnsatisfiedLink` error.

### Solution

- Expand the OS/architecture checks when compiling to produce a specific file for Apple Silicon
- Expand the corresponding OS/architecture checks when loading the binary at runtime from Java code
- Include a CircleCI job to compile on an M1 machine when releasing, also explicitly request an x86 machine for the existing build so it's unambiguous

I've tested this locally - not the CircleCI part, but in terms of compiling and building and then running against some Java code on an M1 Macbook.

~It's definitely incomplete - I haven't touched the Python side although I expect it'll need some changes too - I wanted to get some early feedback at this point.~

#### One-line summary:

Add support for Apple Silicon to `openlineage-sql-java`

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [x] Your comment includes a one-liner for the changelog about the specific purpose of the change (_if necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2023 contributors to the OpenLineage project

### CODE REVIEW

**Comment by mobuchowski** [comment]
@davidjgoss for Python we're passing flag to rust compiler to build universal wheel

```maturin build --target universal2-apple-darwin --out target/wheels --release --strip```

**Comment by mobuchowski** [comment]
@davidjgoss https://app.circleci.com/pipelines/github/OpenLineage/OpenLineage/7582/workflows/fd674fb7-7fc6-4589-9391-1c1299f21ad2/jobs/125291

```
Resource class docker for macos.x86.medium.gen2 is not available for your project, or is not a valid resource class. This message will often appear if the pricing plan for this project does not support docker use. 
```

I don't think you can use `macos.x86.medium.gen2` with docker. The solution probably is to either move from docker executor to machine one, as we did in other CI parts, and install Java ourselves.

**Comment by davidjgoss** [comment]
Thanks @mobuchowski - fixed now.

**Review by mobuchowski — APPROVED** [review]
Thanks @davidjgoss for the contribution.

**Pull request merged**
