### PR TITLE
[Proposal] Add or update license text for SPDX compliance

### PR DESCRIPTION
**Pull request by merobi-hub**
Signed-off-by: Michael Robinson <merobi@gmail.com>

### Problem

License text across the project is either in the outdated block format or missing.

### Solution

This PR adds machine-readable SPDX license lines across the project, replacing block text where needed. 

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [ ] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)

### CODE REVIEW

**Comment by mobuchowski** [comment]
@merobi-hub Can you exclude files `integration/airflow/tests/data/great_expectations/data/yellow_tripdata_sample_2019-01.csv` and `integration/airflow/tests/data/great_expectations/data/yellow_tripdata_sample_2019-02.csv` from this change? Thanks.

**Comment by merobi-hub** [comment]
@mobuchowski Thanks. I removed those .csv files.

**Comment by mobuchowski** [comment]
@merobi-hub you removed them from repository, not the commit 🙂

**Comment by merobi-hub** [comment]
The original files should be back in the repo now.

**Comment by mobuchowski** [comment]
Merged via https://github.com/OpenLineage/OpenLineage/pull/540

**Pull request closed without merging**
