### PR TITLE
Raise on http error rather than fail silently

### PR DESCRIPTION
**Pull request by limx0**
Took me a second to figure out why my events weren't hitting marquez. I think it would be better to raise here?

### CODE REVIEW

**Comment by mobuchowski** [comment]
This is definitely useful, but I think the behavior should be configurable. Some people wouldn't want their tasks to fail due to OL integration timeouting.

**Comment by collado-mike** [comment]
> This is definitely useful, but I think the behavior should be configurable. Some people wouldn't want their tasks to fail due to OL integration timeouting.

My thinking here is that this should be configured at the integration level. The client should most definitely surface the error, but let the individual integrations (Airflow, GE, etc.) determine how to handle the exception. E.g., in the Spark integration, we catch the exceptions and log them, but the Spark tasks continue without failing.

**Comment by julienledem** [comment]
So it sounds like we want to merge this. I think the airflow integration already catches exception at the highest level?

**Review by mobuchowski — APPROVED** [review]

**Review by collado-mike — APPROVED** [review]

**Review by wslulciuc — APPROVED** [review]
Yeah, totally makes sense to raise an exception. Thanks, @limx0!

**Pull request merged**
