### PR TITLE
[PROXY] Fix broken unit tests for the Fluentd proxy

### PR DESCRIPTION
**Pull request by sekikn**
### Problem

Currently, running unit tests for the Fluentd proxy fails as follows:

```
$ bundle exec rake test

...

Started
F
============================================================================================================================
Failure: test: dataset facet validation(OpenlineageParserTest)
/home/sekikn/repos/OpenLineage/proxy/fluentd/test/plugin/test_parser_openlineage.rb:105:in `block in <class:OpenlineageParserTest>'
     102:       'spec_directory' => '../../spec/',
     103:       'validate_dataset_facets' => true,
     104:     )
  => 105:     err = assert_raise Fluent::ParserError do
     106:       @parser.instance.parse(ol_event)
     107:     end
     108:     assert_match "Openlineage validation failed: path \"/outputs/0/facets/ownership/owners", err.message

<Fluent::Plugin::Parser::ParserError> expected but was
<LocalJumpError(<no block given (yield)>)
/home/sekikn/repos/OpenLineage/proxy/fluentd/lib/fluent/plugin/parser_openlineage.rb:36:in `block in parse'
/home/sekikn/.rvm/gems/ruby-3.2.0/gems/fluentd-1.16.2/lib/fluent/plugin/parser_json.rb:78:in `parse'
/home/sekikn/repos/OpenLineage/proxy/fluentd/lib/fluent/plugin/parser_openlineage.rb:34:in `parse'
/home/sekikn/repos/OpenLineage/proxy/fluentd/test/plugin/test_parser_openlineage.rb:106:in `block (2 levels) in <class:OpenlineageParserTest>'

...

Finished in 0.076859175 seconds.
----------------------------------------------------------------------------------------------------------------------------
13 tests, 15 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
53.8462% passed
----------------------------------------------------------------------------------------------------------------------------
169.14 tests/s, 195.16 assertions/s
rake aborted!
```

This is because the current proxy implementation assumes the version of OL's JSON schema is 1.0.5, while the tests refer to the specs in the top level directory which version is 2.0.2 as of this writing. The recent upgrade, e.g., introducing static lineage, loosened schema's constraint on fasets, so the schema validation in fluent-plugin-openlineage-parser passes against expectation and it causes another error (`LocalJumpError` above).

It would be better if the fluentd proxy could handle various versions of OL's schema, but I think it is still worth to clarify this limitation in README and fix the unit tests for ensuring the existing fluent proxy work with OL's spec 1.0.x as of now.

### Solution

* Clarify in README that the current implementation mainly works with OL's spec 1.0.x

* Use the appropriate version of OL's JSON schema for the existing tests

* Add CI workflow for ensuring the fixed tests work

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [x] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [x] You've updated any relevant documentation (_if relevant_)
- [ ] Your comment includes a one-liner for the changelog about the specific purpose of the change (_if necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2023 contributors to the OpenLineage project

### CODE REVIEW

**Review by pawel-big-lebowski — APPROVED** [review]
Thanks for the PR.

I created an issue https://github.com/OpenLineage/OpenLineage/issues/2210 which may be a follow up of this one.

**Comment by JDarDagran** [comment]
@sekikn thanks for finding out broken tests! Indeed, it's not working now due to changes in 2.0+ spec. However, I don't like idea to paste older spec as reference for tests. Instead we should adjust validator code to support 2.0x as mentioned in https://github.com/OpenLineage/OpenLineage/issues/2210.

May I also ask if you're interested in using Fluent proxy?

**Comment by JDarDagran** [comment]
Closing in favor of #2213.

**Comment by sekikn** [comment]
Thank you for your review @JDarDagran @pawel-big-lebowski! I agree with #2213 is a better solution for keeping consistent with the latest spec.

> May I also ask if you're interested in using Fluent proxy?

Yeah, I'd like to leverage it, though I don't have a project to adopt it as of now.
From users' point of view, it may be useful if this plugin is published on rubygems.org so that they can automatically install using `fluentd-gem`. Is it OK for you, or it's not mature enough to be published yet as it's mentioned as experimental?

**Comment by JDarDagran** [comment]
I think we coild publish it. @pawel-big-lebowski ?

**Comment by pawel-big-lebowski** [comment]
Sounds good to me. I consider it still experimental, bcz I don't feel like an expert in writing fluentd plugins. If we had more adopters and possibly some feedback, we could stop mentioning `experimental`. I really like it's within CI now and with @JDarDagran changes (and changes in 2.0 OL Spec) the code looks much better.

**Comment by sekikn** [comment]
Great to hear that! I think it requires updating the release pipeline on CircleCI that I don't have permission unfortunately, but let me know if there were other things I could help ;)

**Pull request closed without merging**
