### PR TITLE
Add AirflowTaskRunFacet facet and deprecate task_info field from AirflowVersionRunFacet

### PR DESCRIPTION
**Pull request by collado-mike**
### Problem

Closes: #986 

### Solution

This adds a new `AirflowTaskRunFacet` with some descriptive information about the task instance. Originally intended to address getting the task attempt number into the OL event, I started adding the tryNumber to the `airflow_version` facet, but I felt that facet has too much information that isn't really relevant to the Airflow version. Instead, I created a new facet that contains information specific to the task and dag run, including the try number. I also fixed some of the ugly serialized fields that we get from the TaskInstance and the DagRun (such as `_BaseOperator__init_kwargs`). I think we should deprecate the `taskInfo` and `operator` fields of the `airflow_version` facet and instead move that information to the `AirflowTaskRunFacet`. 

> **Note:** All schema changes require discussion. Please [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for context.

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

### Checklist

- [ ] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [ ] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [ ] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2022 contributors to the OpenLineage project

### CODE REVIEW

**Comment by mobuchowski** [comment]
I think @JDarDagran is working on the same stuff

**Comment by JDarDagran** [comment]
> I think @JDarDagran is working on the same stuff

I do. I'll do my best to post a complete PR beginning of next week.

**Comment by collado-mike** [comment]
@JDarDagran, If we don't go with this one, can you post something even if it's not complete? Or can we converge on a structure and name for the facet? Some of the work we have is blocked on this being done

**Comment by collado-mike** [comment]
@JDarDagran any word on this? As mentioned, my current work is blocked due to the lack of task information (specifically the try number) in the existing airflow facet. I'd love to get something merged quickly.

**Comment by JDarDagran** [comment]
@collado-mike, with the next change we were planning to have one composite facet each per run and job for Airflow. Therefore, you should expect following structure for Airflow-specific run facets:
```
{...,
    "run": {
        "facets": {
            "airflow": {
                "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.17.0/integration/airflow",
                "_schemaURL": "https://raw.githubusercontent.com/OpenLineage/OpenLineage/main/spec/OpenLineage.json#/definitions/AirflowRunFacet",
                "task": {
                                  ....
                            }
                       }
                   }
               }
 }
 ```

However, along with the composite facets the old will be sent as they were to keep backwards compatibility for some time. In that case I might advise you to put this into `run->facets->airflow_taskRun` (I'm guessing it could be just `airflow_task` instead, it's already under `run` key`. Then, when composite facets are introduced we'll prepare some sort of dictionary which old fields are translated to new ones. Would that work for you?

**Comment by collado-mike** [comment]
> In that case I might advise you to put this into `run->facets->airflow_taskRun` (I'm guessing it could be just `airflow_task` instead, it's already under `run` key`. Then, when composite facets are introduced we'll prepare some sort of dictionary which old fields are translated to new ones. Would that work for you?

I'd prefer not to start consuming a structure that we know is going to change imminently. If there is a known structure, can you link to a doc that describes it? Can we start with a partial implementation now that matches the expected structure, but doesn't yet contain all of the fields? Then, I can start consuming a partial facet and when new fields are added, the existing processing jobs will just continue consuming the information needed.

**Comment by collado-mike** [comment]
> For this I'd need some more context. Are those renamed fields going to be widely used and OL should take care of parsing them into some nicely named fields even if they change in time in Airflow? I'd rather prefer not to handle too often whenever Airflow renames some clearly internal fields.

That's a fine point. I'm specifically referring to these fields here: https://github.com/OpenLineage/OpenLineage/pull/1310/files#diff-0fbcf9a73ef2239bf62fd00088867c6e2bb6db16549fa46c21d3d614be98826cR83-R94 . The init args and the upstream/downstream tasks are all likely to be consumed by someone (the latter is definitely on our roadmap).

**Comment by JDarDagran** [comment]
> That's a fine point. I'm specifically referring to these fields here: https://github.com/OpenLineage/OpenLineage/pull/1310/files#diff-0fbcf9a73ef2239bf62fd00088867c6e2bb6db16549fa46c21d3d614be98826cR83-R94 . The init args and the upstream/downstream tasks are all likely to be consumed by someone (the latter is definitely on our roadmap).

Okay then, let's stick to the cleaner names in OL.

**Comment by mobuchowski** [comment]
This is superseded by https://github.com/OpenLineage/OpenLineage/pull/1410 and https://github.com/OpenLineage/OpenLineage/pull/1413 right?

**Comment by JDarDagran** [comment]
> This is superseded by #1410 and #1413 right?

That's correct, I'm closing the issue.

**Pull request closed without merging**
