### PR TITLE
Introduce new output visitors: AlterTableAddPartitionCommandVisitor and AlterTableSetLocationCommandVisitor

### PR DESCRIPTION
**Pull request by nataliezeller1**
### Problem

Introduce new output visitors:
**AlterTableAddPartitionCommandVisitor** - extracts tables from spark command 'AlterTableAddPartitionCommand'. Example sql: `ALTER TABLE t ADD IF NOT EXISTS PARTITION (a='b')`
**AlterTableSetLocationCommandVisitor** - extracts table names from spark command 'AlterTableSetLocationCommand'. Example sql: `ALTER TABLE t SET LOCATION '...'`

### Solution

Please describe your change as it relates to the problem, or bug fix, as well as any dependencies. If your change requires a schema change, please describe the schema modifcation(s) and whether it's a _backwards-incompatible_ or _backwards-compatible_ change, then select one of the following:

> **Note:** All schema changes require discussion. Please [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for context.

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

### Checklist

- [ ] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [ ] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [ ] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] Your comment includes a one-liner for the changelog about the specific purpose of the change (_if necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2023 contributors to the OpenLineage project

### CODE REVIEW

**Comment by pawel-big-lebowski** [comment]
Hi @nataliezeller1,

Thank You for submitting a PR. I see your code includes output datasets within OpenLineage events for `alter table set location / add partition` commands, while it still does not contain any information on partitions nor locations . What's the usage scenario behind that?

**Comment by nataliezeller1** [comment]
> Hi @nataliezeller1,
> 
> Thank You for submitting a PR. I see your code includes output datasets within OpenLineage events for `alter table set location / add partition` commands, while it still does not contain any information on partitions nor locations . What's the usage scenario behind that?

hi @pawel-big-lebowski 
The purpose of adding these visitors is to extract the affected tables from the commands, to be reported as outlets. 
We are using a custom transport for sending the data to OpenMetadata, their lineage api requires only the table name.

**Comment by allisonsuarez** [comment]
> > Hi @nataliezeller1,
> > Thank You for submitting a PR. I see your code includes output datasets within OpenLineage events for `alter table set location / add partition` commands, while it still does not contain any information on partitions nor locations . What's the usage scenario behind that?
> 
> hi @pawel-big-lebowski The purpose of adding these visitors is to extract the affected tables from the commands, to be reported as outlets. We are using a custom transport for sending the data to OpenMetadata, their lineage api requires only the table name.

We also want these commands as well as the `AlterTableDropPartitionCommand` for the same purpose, or at least a way to configure visitors for these commands, which seems tl not be possible right now because they are not on the BaseVisitorFactory.

**Review by pawel-big-lebowski — APPROVED** [review]
Please do add some notice in supported commands and visitors code clarifying that the generated events will not contain partition nor location information. 

Assuming a goal is to get info on modified datasets, the code looks really well 💯 🔢 🥇

**Comment by nataliezeller1** [comment]
> Please do add some notice in supported commands and visitors code clarifying that the generated events will not contain partition nor location information.
> 
> Assuming a goal is to get info on modified datasets, the code looks really well 💯 🔢 🥇

Thanks! I've added comments

**Comment by pawel-big-lebowski** [comment]
@nataliezeller1 Could you please fix DCO for two commits? Please click details on failing DCO to see the instructions required.

**Comment by nataliezeller1** [comment]
> @nataliezeller1 Could you please fix DCO for two commits? Please click details on failing DCO to see the instructions required.

DCO was fixed but now integration tests fail, doesn't seem related to my changes...

**Comment by pawel-big-lebowski** [comment]
Some integration tests required manual trigger. They succeeded and got merged.
Great job. 
Congrats @nataliezeller1 🚀 👍 💯 🥇

**Pull request merged**
