### PR TITLE
add `dependabot.yml` to configure Dependabot

### PR DESCRIPTION
**Pull request by merobi-hub**
Signed-off-by: Michael Robinson <merobi@gmail.com>

### Problem

The LFAI requires automated dependency monitoring, which we have not yet implemented. GitHub's built-in solution, Dependabot, appears to be relatively easy to deploy and configure, and we are already using it in Marquez (for security updates only). The tool can be turned on in GitHub in the Settings tab, and all configuration can be done in a single YAML file in the `.github` directory.

Closes: #1179 

### Solution

This change adds a `dependabot.yml` file to `.github` containing a link to a guide to configuring the tool, examples (commented) of configurations for two packages, and an entry to configure Gradle monitoring in the Java client. A list of all the supported package managers is also included. **In comments, would you please share feedback on the included configuration for Gradle along with the names of any additional package managers that should be included and, finally, which dependencies to ignore, if any, for each?** Thank you in advance for your help with this project.

> **Note:** All schema changes require discussion. Please [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for context.

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

### CODE REVIEW

**Comment by mobuchowski** [comment]
`client/java` - gradle
`client/python` - pip
`integration/spark` - gradle (I think it won't easily work due to our insane structure)
`integration/flink` - gradle
`integration/sql` - cargo
`integration/common` - pip
`integration/airflow` - pip
`integration/dbt` - pip

**Comment by mobuchowski** [comment]
`which dependencies to ignore, if any, for each?` - would be nice to have a `dry-run` - to see what it will suggest

**Comment by merobi-hub** [comment]
@mobuchowski I added a `dependabot.yml` to main on my fork and turned it on because it won't let you do it on a branch. So far it's opened PRs to update Spark and Flink dependencies: https://github.com/merobi-hub/OpenLineage/pulls
Screen Shot 2022-10-27 at 17 06 37

**Comment by mobuchowski** [comment]
Thanks, those dependencies do make sense to update.

**Comment by mobuchowski** [comment]
@merobi-hub So far, the bot does not break anything, but mostly bumps the test requirements, that do not affect runtime application much

**Comment by merobi-hub** [comment]
@mobuchowski it's now capturing more dependencies (not sure when you last checked). Do you think we should eliminate some ecosystems or dependencies from monitoring? Or do you think we should try to turn on version monitoring in addition to security monitoring?
screencapture-github-merobi-hub-OpenLineage-pulls-2022-10-28-11_10_16

**Comment by mobuchowski** [comment]
@merobi-hub let's merge it and tweak the behavior later.

**Review by mobuchowski — APPROVED** [review]

**Pull request merged**
