### PR TITLE
Create ownership facets

### PR DESCRIPTION
**Pull request by julienledem**
### Problem
capture ownership of jobs and datasets.

Closes: #952 

### Solution

I'm proposing to add an ownership facet to both Dataset and Job to capture this

- [x]  modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

### Checklist

- [ ] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [ ] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [ ] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

### CODE REVIEW

**Comment by mobuchowski** [comment]
@julienledem I think description should reference `URN` only as example, as we aren't enforcing those to be in any particular format. And if we want to enforce it, then it should be explicitely specified, as well as having the reasoning explained

**Comment by wjohnson** [comment]
Is there an integration that you had in mind when writing this spec?

I can see from the Databricks side that we can extract who RAN the job but that's not necessarily the owner of the job.

Do you envision the end user providing this information at runtime?

**Comment by julienledem** [comment]
@mobuchowski I have updated the description. The goal is to have unique identifiers (as now mentioned in the description).

**Review by wslulciuc — APPROVED** [review]
Nice, @julienledem ❤️

QQ: [Marquez](https://github.com/MarquezProject/marquez) currently associates ownership to a namespace for datasets and jobs. Should we also consider adding an ownership facet for namespaces?

**Comment by julienledem** [comment]
That's a good question @wslulciuc.  I'm not sure what's the right thing to do. I think we do need to capture Namespace related metadata in some way

**Pull request merged**
