### PR TITLE
[INTEGRATION][COMMON] Improve SqlParser to extract output table more precisely

### PR DESCRIPTION
**Pull request by sekikn**
Signed-off-by: Kengo Seki <sekikn@apache.org>

### Problem

Currently, SqlParser uses `INTO` as the only keyword to extract output table. But it can't deal with the following cases.

* For BigQuery, `INTO` after `INSERT` (and also `MERGE`) can be omitted.
  https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#insert_statement

* BigQuery and Snowflake support the `UPDATE` statement, which is not accompanied with `INTO`.

### Solution

With this PR, SqlParser can extract output tables correctly from the INSERT w/o INTO and UPDATE statements.

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [x] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)

### CODE REVIEW

**Comment by mobuchowski** [comment]
Thanks for the contribution. Currently, we have different effort to replace this SQL parser. https://github.com/OpenLineage/OpenLineage/pull/644

**Comment by sekikn** [comment]
Cool! I totally missed that.
#644 is close to be merged? If so, I'll close this PR.

**Comment by mobuchowski** [comment]
I think we should still merge your PR, since the current implementation will serve as a fallback implementation.

**Review by mobuchowski — APPROVED** [review]

**Comment by sekikn** [comment]
Thank you for reviewing and merging!

**Pull request merged**
