### PR TITLE
[PROPOSAL][ALL] Convert and Add SPDX Licenses

### PR DESCRIPTION
**Pull request by merobi-hub**
### Problem

The Apache 2.0 licenses used in the project have the outdated block format. In addition, many files contain no license. 

### Solution

This PR adds up-to-date, machine-readable SPDX licenses across the project, revising block-text licenses where they existed and inserting new SPDX licenses where no license existed previously.

### Checklist

- [x ] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [ x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ n/a] Your changes are accompanied by tests (_if relevant_)
- [ n/a] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ n/a] You've updated any relevant documentation (_if relevant_)
- [ n/a] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ n/a] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)

### CODE REVIEW

**Comment by merobi-hub** [comment]
Sign-off message added as comment to second commit. Apologies.

**Review by mobuchowski — APPROVED** [review]
We might want to put linting step later that would check for that licence identifier.

**Comment by merobi-hub** [comment]
Sorry about the new conflicts. I was following the instructions for fixing the sign-off issue, which say to rebase then force push.

**Comment by collado-mike** [comment]
> Sorry about the new conflicts. I was following the instructions for fixing the sign-off issue, which say to rebase then force push.

LOL, You don't have to apologize about conflicts or DCO issues or force pushes or any of that stuff. We all generate conflicts and my PRs have more force-pushes than anyone 😂 . Also https://twitter.com/PeladoCollado/status/1480668064899223553?s=20 😂

**Comment by mobuchowski** [comment]
@merobi-hub There are some duplicated files in this PR, like https://github.com/OpenLineage/OpenLineage/pull/475/files#diff-8edbf014aa57cefee9bc1b42756fbeff5821bcc23196367aadda4a73d85a15a4 - could you remove them?

**Comment by merobi-hub** [comment]
@mobuchowski Thanks for catching that issue. I think all the duplicate files and directories are gone now.

**Comment by merobi-hub** [comment]
Created a new PR for this change.

**Pull request closed without merging**
