### PR TITLE
spark: add Snowflake Relation Visitor

### PR DESCRIPTION
**Pull request by hmoazam**
### Problem

OpenLineage's Spark integration does not currently support Snowflake. 

### Solution

Implemented the SnowflakeRelationVisitor to support lineage for the [Snowflake Spark connector](https://github.com/snowflakedb/spark-snowflake).

There are two paths in OpenLineage to the SnowflakeRelationVisitor:
- Write events reach the SaveIntoDataSourceCommandVisitor, which routes the command to the `createSnowflakeDatasets` method. 
- Read events trigger SnowflakeRelationVisitor's apply method. 

The implementation has been tested locally and on Azure Databricks. 

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [x] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [x] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

### CODE REVIEW

**Comment by hmoazam** [comment]
Thank you @wjohnson for your help getting this PR in!

**Comment by hmoazam** [comment]
I'm not sure why one of the integration tests on spark 2.4.6 is failing. It doesn't seem to be related to the Snowflake package I've added.

**Comment by mobuchowski** [comment]
@pawel-big-lebowski maybe you have some idea 😉

**Comment by pawel-big-lebowski** [comment]
The error is:
```
 java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapred.FileInputFormat
      at io.openlineage.spark.agent.lifecycle.LibraryTest.testRdd(LibraryTest.java:113)
```
which is similar to the one here `https://stackoverflow.com/questions/36427291/illegalaccesserror-to-guavas-stopwatch-from-org-apache-hadoop-mapreduce-lib-inp` which is related to guava version change. 

I think it's worth checking first if `net.snowflake:spark-snowflake` did not introduce another guava version on the class path.

**Review by mobuchowski — APPROVED** [review]

**Comment by hmoazam** [comment]
Thank you @mobuchowski for helping fix the gradle dependencies!

**Pull request merged**
