### PR TITLE
Bug/fix ignored event adaptive spark plan databricks

### PR DESCRIPTION
**Pull request by algorithmy1**
### Problem

While implementing the current OpenLineage Spark integration in Databricks, we've made an interesting observation regarding event filtering and its behavior with narrow and wide transformations:

For a narrow transformation (without shuffle), the event is execute_insert_into_hadoop_fs_relation_command and it doesn't include adaptive_spark_plan.
For a wide transformation (with shuffle), the event is adaptive_spark_plan and doesn't have execute_insert_into_hadoop_fs_relation_command.
We've identified that the adaptive_spark_plan is actively filtered out in the DatabricksEventFilter class. This results in the event being completely ignored due to this line:

Closes: #2058

### Solution

Short-term fix: Remove adaptive_spark_plan from the excludedNodes in DatabricksEventFilter.

#### One-line summary:

Remove adaptive_spark_plan from the excludedNodes in DatabricksEventFilter.

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [x] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [x] Your comment includes a one-liner for the changelog about the specific purpose of the change (_if necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [x] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2023 contributors to the OpenLineage project

### CODE REVIEW

**Comment by mobuchowski** [comment]
@algorithmy1 could you run `./gradlew spotlessApply` on the changes?

**Comment by algorithmy1** [comment]
```
terra@MacBook-Pro-M3 spark % java -version
java version "1.8.0_381"
Java(TM) SE Runtime Environment (build 1.8.0_381-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.381-b09, mixed mode)
```

Can you tell me which java version should I use please ?

**Comment by algorithmy1** [comment]
@mobuchowski ERROR: Missing environment variable {i}
Can you please check what does it come from ?

**Review by mobuchowski — APPROVED** [review]

**Comment by pawel-big-lebowski** [comment]
Filtering `adaptive_spark_plan` has been turned on some time ago to reduce amount of irrelevant events being generated due to  Databricks Runtime & delta internals. Unfortunately, at that time we had no databricks integration tests to document the expected behaviour. But now we do. While working on another databricks test I found that a simple spark job emits dozens of `adaptive_spark_plan` events. So I would like to turn filtering `adaptive_spark_plan` on again, while keeping this feature still valid. 

@algorithmy1:
 * Is there any way to distinguish `adaptive_spark_plan` events you found important for wide transformations from others? 
 * Can I assume I can turn it on in a way your tests are still passing or do you think any additional check is required?

**Pull request merged**
