### PR TITLE
Refactor java builds to eliminate duplication in java publishing

### PR DESCRIPTION
**Pull request by collado-mike**
### Problem
The client and spark integration publish jobs never run until we are ready to do a release, meaning that bugs in the scripts aren't caught until we need to do a release. The logic also gets out of sync between them.

### Solution
Builds on https://github.com/OpenLineage/OpenLineage/pull/356

This consolidates the publishing tasks for both the java client and the spark integration so that the same task is run for publishing snapshots and full releases. This also reuses the client jar built in the earliest task across the testing and the publishing tasks. 

To speed up the Spark unit test build, I changed the `LibraryTest` and `SparkReadWriteIntegTest` to run during the `integrationTest` phase. The tests don't substantially increase the time of the `integrationTest` task, as the setup time dominates the time of that task, but removing them from the unit tests do significantly reduce the time of that task. Since the integration tests are dependent on the unit tests, this does reduce the overall build time.

See https://app.circleci.com/pipelines/github/OpenLineage/OpenLineage/1299/workflows/9149eef1-2dde-45d9-9c1a-94d489495163 where the unit tests ran with the original setup

and  see https://app.circleci.com/pipelines/github/OpenLineage/OpenLineage/1300/workflows/f02fd3c1-bdf6-45be-b6a9-8cb4181e2d9b where the unit tests ran with the reduced time.

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [x] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [x] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)

### CODE REVIEW

**Comment by wslulciuc** [comment]
@collado-mike: Nice! We go from a `13m 17s` build time down to `6m 33s`, that's HUGE! Should we move the PR out of draft so we can merge?

**Comment by collado-mike** [comment]
> @collado-mike: Nice! We go from a `13m 17s` build time down to `6m 33s`, that's HUGE! Should we move the PR out of draft so we can merge?

I honestly don't remember why I left it in draft mode. Let me follow up on this next week and if it's actually ok to merge, I'll move it out of draft mode.

**Review by wslulciuc — APPROVED** [review]
LGTM 👍 

Note, I opened https://github.com/OpenLineage/OpenLineage/issues/614 to unify our `jvm` modules and reduce CI config duplication.

**Comment by mobuchowski** [comment]
@collado-mike want to revisit this?

**Comment by collado-mike** [comment]
I'll come back to this if I have time, but this PR is so outdated I pretty much need to start from scratch anyway.

**Pull request closed without merging**
