### PR TITLE
[PROPOSAL] Add transformation field to ColumnLineageDatasetFacet

### LINKED ISSUE #992: [PROPOSAL] modify the column lecel lineage to include a transformation description.
example:
```
columnLineage: {
   "a:": {
      inputFields: [
         {namespace: "ns", name: "name", "field": "a"},
         ... other inputs
      ],
      transformation: "identical"
    },
    "b": ... other output fields
   }
}
```

proposed schema:
```
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://openlineage.io/spec/facets/1-0-1/ColumnLineageDatasetFacet.json",
  "$defs": {
    "ColumnLineageDatasetFacet": {
      "allOf": [{
        "$ref": "https://openlineage.io/spec/1-0-2/OpenLineage.json#/$defs/DatasetFacet"
      }, {
        "type": "object",
        "properties": {
          "fields": {
            "description": "Column level lineage that maps output fields into input fields used to evaluate them.",
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "properties": {
                "inputFields": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "namespace": {
                        "type": "string",
                        "description": "The input dataset namespace"
                      },
                      "name": {
                        "type": "string",
                        "description": "The input dataset name"
                      },
                      "field": {
                        "type": "string",
                        "description": "The input field"
                      }
                    },
                    "additionalProperties": true,
                    "required": [
                      "namespace", "name", "field"
                    ]
                  },
                  "transformation": {
                    "type": "string",
                    "description": "a string representation of the transformation applied"
                  }
                }
              },
              "required": ["inputFields"]
            }      
          }    
        },
        "additionalProperties": true,
        "required": [
          "fields"
        ]
      }],
      "type": "object"
    }
  },
  "type": "object",
  "properties": {
    "columnLineage": {
      "$ref": "#/$defs/ColumnLineageDatasetFacet"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by julienledem**
### Problem

In column-level lineage we want to be able to capture  a string representation of what the transformation looks like for information purpose.

### Solution

This PR adds a transformation field to the column level lineage facet schema
It is a _backwards-compatible_ change.

closes #992

### Checklist

- [ ] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [ ] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [ ] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

### CODE REVIEW

**Comment by julienledem** [comment]
(I'll fix the DCO before merging)

**Comment by pawel-big-lebowski** [comment]
Could we add a bit more of standarization on possible transformations' types? 
Possible transformation types: `COPY`, `CLEAR_PERSONAL_DATA`, `FUNCTION`, `OTHER`
For the `FUNCTION` type, we could also include function name.

**Comment by mobuchowski** [comment]
@pawel-big-lebowski I think that would be two things: the description of the transformation itself and the type of it. At least that's how I imagine it - the transformation could be text representation of the operation itself, in some machine readable language?

@julienledem is that how that field is going to be used, or is that just a "marker" or a human readable description?

**Comment by wslulciuc** [comment]
I agree with @pawel-big-lebowski and @mobuchowski, it would also be helpful to provide some transformation examples for clarity. As I was thinking of how I would use the _transformation_ field, it wasn't immediately clear on its usage from the description alone.

**Comment by julienledem** [comment]
Yes the goal is to have a human readable description of the transformation. The other issue with my proposal is I added the field on the input field when it is actually meant for the output field level. I may need to change the schema to add that field.

**Comment by julienledem** [comment]
I have created an issue to track that change: https://github.com/OpenLineage/OpenLineage/issues/992

**Comment by julienledem** [comment]
Updated 
@pawel-big-lebowski I did not put FUNCTION or OTHER. I'm thinking having the field optional serves the same purpose as OTHER
FUNCTION is less useful. I would let it in the general category of an expression in the description.

**Review by pawel-big-lebowski — APPROVED** [review]

**Review by mobuchowski — APPROVED** [review]
Looks good to me!

**Pull request merged**
