### PR TITLE
spark: Enable nessie rest catalog

### PR DESCRIPTION
**Pull request by julwin**
### Problem

Nessie catalog is not supported when using spark.

Closes: #2084

### Solution

Please describe your change as it relates to the problem, or bug fix, as well as any dependencies. If your change requires a schema change, please describe the schema modification(s) and whether it's a _backwards-incompatible_ or _backwards-compatible_ change, then select one of the following:

> **Note:** All schema changes require discussion. Please [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for context.

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

#### One-line summary:

Add a new case to the if-else statement in the getDatasetIdentifier() method to handle Nessie catalogs.

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [x] Your comment includes a one-liner for the changelog about the specific purpose of the change (_if necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2023 contributors to the OpenLineage project

### CODE REVIEW

**Review by harels — APPROVED** [review]
thanks for the contribution, this looks great!

**Comment by julwin** [comment]
Unfortunately this did not work as expected: 

```
ERROR PlanUtils3: Catalog iceberg is unsupported
INFO - io.openlineage.spark3.agent.lifecycle.plan.catalog.UnsupportedCatalogException: iceberg 
io.openlineage.spark3.agent.lifecycle.plan.catalog.IcebergHandler.getDatasetIdentifier(IcebergHandler.java:83)
```

@harels can we reopen this? Would a modification like

`else if (catalogConf.get(TYPE).equals("iceberg"))` work, or are there possible issues with other catalogs for iceberg?

**Comment by pawel-big-lebowski** [comment]
Would you be able to include integration test (perhaps similar to this one io.openlineage.spark.agent.SparkIcebergIntegrationTest) that verifies this feature?

**Comment by julwin** [comment]
> Would you be able to include integration test (perhaps similar to this one io.openlineage.spark.agent.SparkIcebergIntegrationTest) that verifies this feature?

I would love to, but I feel like my Java knowledge is too limited to achieve anything meaningful here :(. 

I think the integration test you mentioned would work even with nessie as catalog.

Is there a way for me to build the jar locally so I can test?

**Comment by pawel-big-lebowski** [comment]
yes, please refer to https://github.com/OpenLineage/OpenLineage/tree/main/integration/spark#build

**Pull request merged**
