### PR TITLE
Feature - Airflow S3CopyObject extractor

### PR DESCRIPTION
**Pull request by fhoda**
### Problem

There is no S3 extractor currently for Airflow operators.

### Solution

Created an extractor for the S3CopyObject Operator in Airflow.

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

This has been smoke tested locally in Airflow and in Astronomer (Astro)  with S3 as a custom extractor.

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [x] Your changes are accompanied by tests (_if relevant_)
- [ ] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

### CODE REVIEW

**Comment by mobuchowski** [comment]
@fhoda do you still want to submit this PR?

**Comment by fhoda** [comment]
> @fhoda do you still want to submit this PR?

Yes

**Comment by fhoda** [comment]
@mobuchowski is there anything left for me to do or fix so that this can be merged?

**Comment by fhoda** [comment]
cc @virajmparekh

**Comment by fhoda** [comment]
@mobuchowski, just a friendly bump for his PR. I've rebased and resolved conflicts. Let me know if there is anything else you need from me.

**Review by mobuchowski — APPROVED** [review]

**Comment by mobuchowski** [comment]
Thanks @fhoda !

**Pull request merged**
