### PR TITLE
feat: added support for iceberg rest catalog

### PR DESCRIPTION
**Pull request by juancappi**
### Problem

Currently, Spark Iceberg integration for Openlineage only supports hive and hadoop catalogs. Iceberg also has RestCatalog. It would be good to have it supported for Openlineage also as it is gaining popularity.

Implements: #1940

### Solution
Add `rest` to the existing options of `hive` and `hadoop` in `IcebergHandler.getDatasetIdentifier()`
It's a _backwards-compatible_ change.

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [x] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] Your comment includes a one-liner for the changelog about the specific purpose of the change (_if necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2023 contributors to the OpenLineage project

### CODE REVIEW

**Review by pawel-big-lebowski — APPROVED** [review]

**Comment by pawel-big-lebowski** [comment]
Hi @juancappi,

Thank you for submitting your PR. Circle-ci is failing for pre-commit test which was fixed last week. Could you please rebase your PR onto current main?

**Comment by juancappi** [comment]
@pawel-big-lebowski rebase done. Circle-ci still seems to be failing in the same place.

**Comment by pawel-big-lebowski** [comment]
Congrats @juancappi 🥇 🚀 👍 💯

**Comment by juancappi** [comment]
Thank you @pawel-big-lebowski !

**Pull request merged**
