### PR TITLE
test: Add integration tests for EMR

### PR DESCRIPTION
**Pull request by arturowczarek**
* Spark integration has integration tests for EMR

### Problem

We are missing the integration tests for EMR. Without them some types of bugs remain undetected and we may introduce regressions without knowing it.

### Solution

We should have integration tests. We don't have a sponsor for the AWS infrastructure, so every developer should be able to run them manually using their infrastructure.

**For reviewers**: Start reading from `EmrIntegrationTest` class.

> **Note:** All schema changes require discussion. Please [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for context.

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

### Checklist

- [X] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [X] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [X] Your changes are accompanied by tests (_if relevant_)
- [X] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [X] Your comment includes a one-liner for the changelog about the specific purpose of the change (_not required for changes to tests, docs, or CI config_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2024 contributors to the OpenLineage project

### CODE REVIEW

**Comment by mobuchowski** [comment]
@arturowczarek can we run "regular" integration tests on EMR, or only special tests otherwise located in the `emr_test_jobs` directory?

**Comment by arturowczarek** [comment]
@mobuchowski The loading class locates the files in the specific directory for simplicity. We can extend it if necessary, but passing just the name of the file is convenient, because the name is used to create temporary directory where everything for this test is kept. Otherwise we could have multiple scripts with the same name and they would keep the events under the same location. Alternatively we could have a better strategy for determining the location for the events.

**Comment by mobuchowski** [comment]
Makes sense, I just think we'd also potentially benefit with running a bunch of "regular" integration tests on EMR regularly.

**Comment by arturowczarek** [comment]
Yes, it is one of the methods we could further develop these tests.
There is another challenge we have to find a good solution to - managing resources and determining which tests to run. In some tests I'd like to add, there is a need to have two AWS accounts (to have two separate Glue catalogs). It is not common that developers have access to multiple accounts. In such scenarios they have to skip these tests. I'd also like to create some (possibly) Terraform file to create the infrastructure. I'll do it when we have someone to sponsor it.

**Review by pawel-big-lebowski — COMMENTED** [review]
I think this is huge step forward in improving OL event collection on AWS. 
The code looks good to me.

What system properties are required to be set to run the test?

**Comment by arturowczarek** [comment]
The parameters are listed in `DynamicParameter` enum. Most of them have some reasonable defaults (instance size, EMR version, roles which should be present in every account). Only one is required (`openlineage.tests.bucketName`). Apart from that you have to be authenticated (have ~/.aws/credentials file or use any method described in [Default credentials provider chain](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials-chain.html))

**Pull request merged**
